const DEFAULT_ITEMS = [
  {
    id: 101,
    category: 'anime',
    title: 'Attack on Titan',
    desc: 'Humanity fights for survival behind massive walls while Titans threaten the world.',
    tags: ['Action', 'Drama', 'Dark Fantasy'],
    rating: 9.1,
    year: 2013,
    mal_id: 16498,
    img: ''
  },
  {
    id: 102,
    category: 'anime',
    title: 'Demon Slayer',
    desc: 'A boy becomes a demon slayer to save his sister and avenge his family.',
    tags: ['Action', 'Adventure', 'Supernatural'],
    rating: 8.8,
    year: 2019,
    mal_id: 38000,
    img: ''
  },
  {
    id: 103,
    category: 'anime',
    title: 'Fullmetal Alchemist: Brotherhood',
    desc: 'Two brothers search for the Philosopher’s Stone after a failed alchemy ritual.',
    tags: ['Adventure', 'Fantasy', 'Drama'],
    rating: 9.2,
    year: 2009,
    mal_id: 5114,
    img: ''
  },
  {
    id: 104,
    category: 'anime',
    title: 'My Hero Academia',
    desc: 'A powerless boy attends hero school to become the world’s greatest hero.',
    tags: ['Superhero', 'School', 'Action'],
    rating: 8.3,
    year: 2016,
    mal_id: 31964,
    img: ''
  },
  {
    id: 105,
    category: 'anime',
    title: 'Spy x Family',
    desc: 'A spy, assassin and telepath pretend to be a family while hiding their secrets.',
    tags: ['Comedy', 'Action', 'Slice of Life'],
    rating: 8.5,
    year: 2022,
    mal_id: 51780,
    img: ''
  },
  {
    id: 106,
    category: 'anime',
    title: 'One Piece',
    desc: 'A pirate crew searches for the ultimate treasure in a world of adventure.',
    tags: ['Adventure', 'Fantasy', 'Action'],
    rating: 8.7,
    year: 1999,
    mal_id: 21,
    img: ''
  },
  {
    id: 107,
    category: 'anime',
    title: 'Jujutsu Kaisen',
    desc: 'A student joins a school of sorcerers after swallowing a cursed object.',
    tags: ['Supernatural', 'Action', 'Horror'],
    rating: 8.6,
    year: 2020,
    mal_id: 100922,
    img: ''
  },
  {
    id: 108,
    category: 'anime',
    title: 'Hunter x Hunter',
    desc: 'A young boy becomes a Hunter to find his father and face deadly challenges.',
    tags: ['Adventure', 'Action', 'Fantasy'],
    rating: 9.0,
    year: 2011,
    mal_id: 11061,
    img: ''
  },
  {
    id: 109,
    category: 'anime',
    title: 'Death Note',
    desc: 'A notebook gives its user the power to kill anyone by writing their name in it.',
    tags: ['Psychological', 'Thriller', 'Supernatural'],
    rating: 9.0,
    year: 2006,
    mal_id: 1535,
    img: ''
  },
  {
    id: 110,
    category: 'anime',
    title: 'Naruto',
    desc: 'A young ninja strives to earn respect and become leader of his village.',
    tags: ['Adventure', 'Action', 'Coming of Age'],
    rating: 8.6,
    year: 2002,
    mal_id: 20,
    img: ''
  },
  {
    id: 111,
    category: 'anime',
    title: 'Cowboy Bebop',
    desc: 'Bounty hunters travel the solar system seeking their next paycheck.',
    tags: ['Sci-Fi', 'Action', 'Noir'],
    rating: 8.9,
    year: 1998,
    mal_id: 1,
    img: ''
  },
  {
    id: 112,
    category: 'anime',
    title: 'Steins;Gate',
    desc: 'A group of friends accidentally invent a time machine and face deadly consequences.',
    tags: ['Sci-Fi', 'Thriller', 'Mystery'],
    rating: 9.1,
    year: 2011,
    mal_id: 9253,
    img: ''
  },
  {
    id: 113,
    category: 'anime',
    title: 'Made in Abyss',
    desc: 'A girl and a robot descend into a dangerous abyss to find her mother.',
    tags: ['Adventure', 'Dark Fantasy', 'Mystery'],
    rating: 8.7,
    year: 2017,
    mal_id: 34599,
    img: ''
  },
  {
    id: 114,
    category: 'anime',
    title: 'Mob Psycho 100',
    desc: 'A psychic tries to live a normal life while suppressing overwhelming power.',
    tags: ['Comedy', 'Action', 'Supernatural'],
    rating: 8.6,
    year: 2016,
    mal_id: 34538,
    img: ''
  },
  {
    id: 115,
    category: 'anime',
    title: 'Vinland Saga',
    desc: 'A young warrior seeks revenge during the Viking era in a brutal world of conquest.',
    tags: ['Historical', 'Action', 'Drama'],
    rating: 8.9,
    year: 2019,
    mal_id: 36261,
    img: ''
  },
  {
    id: 201,
    category: 'manga',
    title: 'One Piece',
    desc: 'A pirate captain pursues legendary treasure and freedom on the open sea.',
    tags: ['Adventure', 'Fantasy', 'Action'],
    rating: 9.0,
    year: 1997,
    mal_id: 13,
    img: ''
  },
  {
    id: 202,
    category: 'manga',
    title: 'Chainsaw Man',
    desc: 'A demon hunter with a chainsaw body battles devils for money and survival.',
    tags: ['Action', 'Horror', 'Supernatural'],
    rating: 8.7,
    year: 2018,
    mal_id: 101922,
    img: ''
  },
  {
    id: 203,
    category: 'manga',
    title: 'Jujutsu Kaisen',
    desc: 'Students fight curses while hiding the power of a deadly demon within their school.',
    tags: ['Supernatural', 'Action', 'Fantasy'],
    rating: 8.6,
    year: 2018,
    mal_id: 100922,
    img: ''
  },
  {
    id: 204,
    category: 'manga',
    title: 'Berserk',
    desc: 'A mercenary struggles against demons and fate in a dark, medieval world.',
    tags: ['Dark Fantasy', 'Action', 'Horror'],
    rating: 9.1,
    year: 1989,
    mal_id: 2,
    img: ''
  },
  {
    id: 205,
    category: 'manga',
    title: 'Tokyo Ghoul',
    desc: 'A student survives as a half-ghoul in a city where humans fear monsters.',
    tags: ['Horror', 'Drama', 'Supernatural'],
    rating: 8.3,
    year: 2011,
    mal_id: 22319,
    img: ''
  },
  {
    id: 206,
    category: 'manga',
    title: 'Demon Slayer',
    desc: 'A swordsman joins demon slayers to avenge his family and save his sister.',
    tags: ['Action', 'Supernatural', 'Adventure'],
    rating: 8.7,
    year: 2016,
    mal_id: 40748,
    img: ''
  },
  {
    id: 207,
    category: 'manga',
    title: 'Solo Leveling',
    desc: 'A weak hunter becomes the strongest after discovering a mysterious leveling system.',
    tags: ['Action', 'Fantasy', 'Adventure'],
    rating: 8.5,
    year: 2018,
    mal_id: 149650,
    img: ''
  },
  {
    id: 208,
    category: 'manga',
    title: 'Attack on Titan',
    desc: 'A soldier fights Titans while uncovering secrets behind humanity’s last walls.',
    tags: ['Action', 'Mystery', 'Drama'],
    rating: 9.0,
    year: 2009,
    mal_id: 20315,
    img: ''
  },
  {
    id: 209,
    category: 'manga',
    title: 'My Hero Academia',
    desc: 'A quirkless boy trains to become a hero in a world of superpowered students.',
    tags: ['Superhero', 'School', 'Action'],
    rating: 8.4,
    year: 2014,
    mal_id: 107968,
    img: ''
  },
  {
    id: 210,
    category: 'manga',
    title: 'Spy x Family',
    desc: 'A spy forms a fake family to complete a mission while keeping everyone’s secrets.',
    tags: ['Comedy', 'Action', 'Slice of Life'],
    rating: 8.5,
    year: 2019,
    mal_id: 51794,
    img: ''
  },
  {
    id: 301,
    category: 'tv',
    title: 'Breaking Bad',
    desc: 'A chemistry teacher turns to meth production after a terminal diagnosis.',
    tags: ['Crime', 'Drama', 'Thriller'],
    rating: 9.5,
    year: 2008,
    tmdb_id: 1396,
    img: ''
  },
  {
    id: 302,
    category: 'tv',
    title: 'Stranger Things',
    desc: 'Kids uncover supernatural secrets in their small town while searching for a missing friend.',
    tags: ['Sci-Fi', 'Horror', 'Mystery'],
    rating: 8.7,
    year: 2016,
    tmdb_id: 66732,
    img: ''
  },
  {
    id: 303,
    category: 'tv',
    title: 'The Office',
    desc: 'A documentary crew follows employees working at a mundane paper company.',
    tags: ['Comedy', 'Workplace', 'Mockumentary'],
    rating: 8.8,
    year: 2005,
    tmdb_id: 2316,
    img: ''
  },
  {
    id: 304,
    category: 'tv',
    title: 'Rick and Morty',
    desc: 'A genius scientist drags his grandson on dangerous adventures across the multiverse.',
    tags: ['Comedy', 'Sci-Fi', 'Animation'],
    rating: 9.2,
    year: 2013,
    tmdb_id: 60625,
    img: ''
  },
  {
    id: 305,
    category: 'tv',
    title: 'The Mandalorian',
    desc: 'A lone bounty hunter protects a mysterious child in the outer reaches of the galaxy.',
    tags: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 8.8,
    year: 2019,
    tmdb_id: 82856,
    img: ''
  },
  {
    id: 306,
    category: 'tv',
    title: 'Arcane',
    desc: 'Two sisters fight to survive in a city divided by magic, power and rising unrest.',
    tags: ['Animation', 'Action', 'Fantasy'],
    rating: 9.3,
    year: 2021,
    tmdb_id: 94605,
    img: ''
  },
  {
    id: 307,
    category: 'tv',
    title: 'Chernobyl',
    desc: 'A dramatization of the nuclear disaster and the human cost of the cover-up.',
    tags: ['History', 'Drama', 'Thriller'],
    rating: 9.4,
    year: 2019,
    tmdb_id: 87108,
    img: ''
  },
  {
    id: 308,
    category: 'tv',
    title: 'The Witcher',
    desc: 'A monster hunter struggles with fate and politics in a dark fantasy world.',
    tags: ['Fantasy', 'Action', 'Adventure'],
    rating: 8.2,
    year: 2019,
    tmdb_id: 71912,
    img: ''
  },
  {
    id: 309,
    category: 'tv',
    title: 'Dark',
    desc: 'A time-travel mystery unravels family secrets across several generations.',
    tags: ['Sci-Fi', 'Mystery', 'Thriller'],
    rating: 8.8,
    year: 2017,
    tmdb_id: 70523,
    img: ''
  },
  {
    id: 310,
    category: 'tv',
    title: 'The Boys',
    desc: 'A group fights corrupt superheroes who abuse their power in a warped world.',
    tags: ['Action', 'Comedy', 'Drama'],
    rating: 8.7,
    year: 2019,
    tmdb_id: 76479,
    img: ''
  },
  {
    id: 311,
    category: 'tv',
    title: 'Loki',
    desc: 'The god of mischief is forced to repair the timeline after stealing the Tesseract.',
    tags: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 8.3,
    year: 2021,
    tmdb_id: 84958,
    img: ''
  },
  {
    id: 312,
    category: 'tv',
    title: 'Ozark',
    desc: 'A family moves to the Ozarks to launder money for a drug cartel while danger closes in.',
    tags: ['Crime', 'Drama', 'Thriller'],
    rating: 8.4,
    year: 2017,
    tmdb_id: 69740,
    img: ''
  },
  {
    id: 313,
    category: 'tv',
    title: 'Better Call Saul',
    desc: 'A small-time lawyer transforms into a morally flexible attorney in the criminal underworld.',
    tags: ['Crime', 'Drama', 'Legal'],
    rating: 8.8,
    year: 2015,
    tmdb_id: 60059,
    img: ''
  },
  {
    id: 314,
    category: 'tv',
    title: 'The Crown',
    desc: 'A dramatized look at the reign of Queen Elizabeth II and the challenges of the royal family.',
    tags: ['History', 'Drama', 'Biographical'],
    rating: 8.6,
    year: 2016,
    tmdb_id: 65494,
    img: ''
  },
  {
    id: 315,
    category: 'tv',
    title: 'Peaky Blinders',
    desc: 'A criminal family rises in post-WWI Birmingham while battling rivals and the law.',
    tags: ['Crime', 'Drama', 'Historical'],
    rating: 8.8,
    year: 2013,
    tmdb_id: 60574,
    img: ''
  },
  {
    id: 316,
    category: 'tv',
    title: 'Black Mirror',
    desc: 'Standalone stories explore technology’s dark side and its impact on society.',
    tags: ['Sci-Fi', 'Thriller', 'Drama'],
    rating: 8.8,
    year: 2011,
    tmdb_id: 42009,
    img: ''
  },
  {
    id: 317,
    category: 'tv',
    title: 'The Expanse',
    desc: 'A conspiracy threatens the fragile peace between Earth, Mars and the Belt.',
    tags: ['Sci-Fi', 'Drama', 'Mystery'],
    rating: 8.5,
    year: 2015,
    tmdb_id: 63639,
    img: ''
  },
  {
    id: 318,
    category: 'tv',
    title: 'Fargo',
    desc: 'Crime stories intersect in small-town America, each more bizarre than the last.',
    tags: ['Crime', 'Drama', 'Dark Comedy'],
    rating: 8.9,
    year: 2014,
    tmdb_id: 60622,
    img: ''
  },
  {
    id: 319,
    category: 'tv',
    title: 'Westworld',
    desc: 'A theme park of lifelike androids spirals into chaos as guests lose control.',
    tags: ['Sci-Fi', 'Mystery', 'Thriller'],
    rating: 8.6,
    year: 2016,
    tmdb_id: 63247,
    img: ''
  },
  {
    id: 320,
    category: 'tv',
    title: 'House of the Dragon',
    desc: 'A Targaryen civil war erupts over the Iron Throne generations before Game of Thrones.',
    tags: ['Fantasy', 'Drama', 'Historical'],
    rating: 8.4,
    year: 2022,
    tmdb_id: 94997,
    img: ''
  }
];
